services:
  ### | PostgresSQL as cleaner Database | ###
  app_postgresql:
    image: postgres:15
    container_name: ${CONTAINER_NAME_POSTGRESQL}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ../volumes/postgres_data:/var/lib/postgresql/data
      - ../sql-files/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - ${NETWORK_NAME}
    env_file:
      - ../../.env

  ### | Web-Server as Express.js library | ###
  app_server:
    build:
      context: ../../server
      dockerfile: ../docker/dockerfiles/Dockerfile-server-${DOCKER_MODE}
    container_name: ${CONTAINER_NAME_SERVER}
    restart: unless-stopped
    volumes:
      - ../../server:/server
      - /server/node_modules
    ports:
      - "0.0.0.0:${VITE_SERVER_PORT}:${VITE_SERVER_PORT}"
    networks:
      - ${NETWORK_NAME}
    depends_on:
      - ${CONTAINER_NAME_POSTGRESQL}
    env_file:
      - ../../.env

  ### | Web-Client as React.js framework | ###
  app_client:
    build:
      context: ../../client
      dockerfile: ../docker/dockerfiles/Dockerfile-client-${DOCKER_MODE}
    container_name: ${CONTAINER_NAME_CLIENT}
    restart: unless-stopped
    volumes:
      - ../../client:/client
      - /client/node_modules
    ports:
      - "0.0.0.0:${VITE_CLIENT_PORT}:${VITE_CLIENT_PORT}"
    stdin_open: true
    tty: true
    networks:
      - ${NETWORK_NAME}
    env_file:
      - ../../.env
    environment:
      - DOCKER_HOST=true
    depends_on:
      - ${CONTAINER_NAME_SERVER}

networks:
  app_network:
    external: true